time: "07:47" // Время ежедневного запуска

grpc:
  ip: "0.0.0.0"           // Host
  port: 50051             // Порт, который будет прослушивать сервис

reports:
  - report_name: "название отчета"
    spreadsheet_id: "google-spreadsheet-id"
    google_service_key: "service_key.json"
    project_id: 'bq-project-id'
    dataset_id: 'bq-dataset-id'
    table_id: 'bq_all_clients_table'
    days: 7

  - report_name: "название отчета 2"
    spreadsheet_id: "google-spreadsheet-id"
    google_service_key: "service_key.json"
    project_id: 'bq-project-id'
    dataset_id: 'bq-dataset-id'
    table_id: 'bq_all_clients_table'
    period: 15