google_sheets:
  service_key_path: '/home/viktor/Programming/.keys/mgcom-realestate-dwh-script.json'
  spreadsheet_id: '1c3Nl0KyO_DZL5WWxOX_xjH6Qpa9Ke4PMVndK2yr15lU'

bq:
  service_key_path: 'path to file token'
  project_id: 'project'
  dataset_id: 'dataset'
  table_id: 'table'

tg:
  token: 'token'
  chat: 0000000