// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/grpc/soloway.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SolowayServiceClient is the client API for SolowayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolowayServiceClient interface {
	PushPlacementStatByDayToBQ(ctx context.Context, in *PushPlacementStatByDayToBQRequest, opts ...grpc.CallOption) (*PushPlacementStatByDayToBQResponse, error)
}

type solowayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSolowayServiceClient(cc grpc.ClientConnInterface) SolowayServiceClient {
	return &solowayServiceClient{cc}
}

func (c *solowayServiceClient) PushPlacementStatByDayToBQ(ctx context.Context, in *PushPlacementStatByDayToBQRequest, opts ...grpc.CallOption) (*PushPlacementStatByDayToBQResponse, error) {
	out := new(PushPlacementStatByDayToBQResponse)
	err := c.cc.Invoke(ctx, "/soloway.SolowayService/PushPlacementStatByDayToBQ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolowayServiceServer is the server API for SolowayService service.
// All implementations must embed UnimplementedSolowayServiceServer
// for forward compatibility
type SolowayServiceServer interface {
	PushPlacementStatByDayToBQ(context.Context, *PushPlacementStatByDayToBQRequest) (*PushPlacementStatByDayToBQResponse, error)
	mustEmbedUnimplementedSolowayServiceServer()
}

// UnimplementedSolowayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSolowayServiceServer struct {
}

func (UnimplementedSolowayServiceServer) PushPlacementStatByDayToBQ(context.Context, *PushPlacementStatByDayToBQRequest) (*PushPlacementStatByDayToBQResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushPlacementStatByDayToBQ not implemented")
}
func (UnimplementedSolowayServiceServer) mustEmbedUnimplementedSolowayServiceServer() {}

// UnsafeSolowayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolowayServiceServer will
// result in compilation errors.
type UnsafeSolowayServiceServer interface {
	mustEmbedUnimplementedSolowayServiceServer()
}

func RegisterSolowayServiceServer(s grpc.ServiceRegistrar, srv SolowayServiceServer) {
	s.RegisterService(&SolowayService_ServiceDesc, srv)
}

func _SolowayService_PushPlacementStatByDayToBQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushPlacementStatByDayToBQRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolowayServiceServer).PushPlacementStatByDayToBQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soloway.SolowayService/PushPlacementStatByDayToBQ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolowayServiceServer).PushPlacementStatByDayToBQ(ctx, req.(*PushPlacementStatByDayToBQRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SolowayService_ServiceDesc is the grpc.ServiceDesc for SolowayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SolowayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "soloway.SolowayService",
	HandlerType: (*SolowayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushPlacementStatByDayToBQ",
			Handler:    _SolowayService_PushPlacementStatByDayToBQ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/soloway.proto",
}
