// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/grpc/soloway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Конфигурация для BigQuery
type BqConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId  string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`    // required
	DatasetId  string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`    // required
	TableId    string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`          // required
	ServiceKey string `protobuf:"bytes,4,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"` // required Название файла сервисного ключа
}

func (x *BqConfig) Reset() {
	*x = BqConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_soloway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BqConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BqConfig) ProtoMessage() {}

func (x *BqConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_soloway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BqConfig.ProtoReflect.Descriptor instead.
func (*BqConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_soloway_proto_rawDescGZIP(), []int{0}
}

func (x *BqConfig) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BqConfig) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *BqConfig) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *BqConfig) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

type GsConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpreadsheetId string `protobuf:"bytes,1,opt,name=spreadsheet_id,json=spreadsheetId,proto3" json:"spreadsheet_id,omitempty"` // required
	ServiceKey    string `protobuf:"bytes,2,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`          // required Название файла сервисного ключа
}

func (x *GsConfig) Reset() {
	*x = GsConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_soloway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GsConfig) ProtoMessage() {}

func (x *GsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_soloway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GsConfig.ProtoReflect.Descriptor instead.
func (*GsConfig) Descriptor() ([]byte, []int) {
	return file_api_grpc_soloway_proto_rawDescGZIP(), []int{1}
}

func (x *GsConfig) GetSpreadsheetId() string {
	if x != nil {
		return x.SpreadsheetId
	}
	return ""
}

func (x *GsConfig) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

type Period struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DateFrom string `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"` //  required  is date represented in the ISO-8601 format
	DateTill string `protobuf:"bytes,2,opt,name=date_till,json=dateTill,proto3" json:"date_till,omitempty"` //  required  is date represented in the ISO-8601 format
}

func (x *Period) Reset() {
	*x = Period{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_soloway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_soloway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_api_grpc_soloway_proto_rawDescGZIP(), []int{2}
}

func (x *Period) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *Period) GetDateTill() string {
	if x != nil {
		return x.DateTill
	}
	return ""
}

type PushPlacementStatByDayToBQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BqConfig *BqConfig `protobuf:"bytes,1,opt,name=bq_config,json=bqConfig,proto3" json:"bq_config,omitempty"` // required  Конфигурация для BigQuery
	GsConfig *GsConfig `protobuf:"bytes,2,opt,name=gs_config,json=gsConfig,proto3" json:"gs_config,omitempty"` // required  Конфигурация для CloudStorage
	Period   *Period   `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`                     //  required  Период данных для сбора
}

func (x *PushPlacementStatByDayToBQRequest) Reset() {
	*x = PushPlacementStatByDayToBQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_soloway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushPlacementStatByDayToBQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPlacementStatByDayToBQRequest) ProtoMessage() {}

func (x *PushPlacementStatByDayToBQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_soloway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPlacementStatByDayToBQRequest.ProtoReflect.Descriptor instead.
func (*PushPlacementStatByDayToBQRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_soloway_proto_rawDescGZIP(), []int{3}
}

func (x *PushPlacementStatByDayToBQRequest) GetBqConfig() *BqConfig {
	if x != nil {
		return x.BqConfig
	}
	return nil
}

func (x *PushPlacementStatByDayToBQRequest) GetGsConfig() *GsConfig {
	if x != nil {
		return x.GsConfig
	}
	return nil
}

func (x *PushPlacementStatByDayToBQRequest) GetPeriod() *Period {
	if x != nil {
		return x.Period
	}
	return nil
}

type PushPlacementStatByDayToBQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk     bool     `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	Warnings []string `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"` // Возникшие ошибки
}

func (x *PushPlacementStatByDayToBQResponse) Reset() {
	*x = PushPlacementStatByDayToBQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_soloway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushPlacementStatByDayToBQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPlacementStatByDayToBQResponse) ProtoMessage() {}

func (x *PushPlacementStatByDayToBQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_soloway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPlacementStatByDayToBQResponse.ProtoReflect.Descriptor instead.
func (*PushPlacementStatByDayToBQResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_soloway_proto_rawDescGZIP(), []int{4}
}

func (x *PushPlacementStatByDayToBQResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *PushPlacementStatByDayToBQResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_api_grpc_soloway_proto protoreflect.FileDescriptor

var file_api_grpc_soloway_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x77,
	0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x6f, 0x6c, 0x6f, 0x77, 0x61,
	0x79, 0x22, 0x84, 0x01, 0x0a, 0x08, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x52, 0x0a, 0x08, 0x47, 0x73, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x70, 0x72, 0x65, 0x61, 0x64, 0x73, 0x68,
	0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x70,
	0x72, 0x65, 0x61, 0x64, 0x73, 0x68, 0x65, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x42, 0x0a, 0x06,
	0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6c, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6c, 0x6c,
	0x22, 0xac, 0x01, 0x0a, 0x21, 0x50, 0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x42, 0x79, 0x44, 0x61, 0x79, 0x54, 0x6f, 0x42, 0x51, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x09, 0x62, 0x71, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6f, 0x6c, 0x6f,
	0x77, 0x61, 0x79, 0x2e, 0x42, 0x71, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x62, 0x71,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2e, 0x0a, 0x09, 0x67, 0x73, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6f, 0x6c, 0x6f,
	0x77, 0x61, 0x79, 0x2e, 0x47, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x08, 0x67, 0x73,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x77, 0x61, 0x79,
	0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22,
	0x55, 0x0a, 0x22, 0x50, 0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x42, 0x79, 0x44, 0x61, 0x79, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61,
	0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x32, 0x87, 0x01, 0x0a, 0x0e, 0x53, 0x6f, 0x6c, 0x6f, 0x77,
	0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x75, 0x0a, 0x1a, 0x50, 0x75, 0x73,
	0x68, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x42, 0x79,
	0x44, 0x61, 0x79, 0x54, 0x6f, 0x42, 0x51, 0x12, 0x2a, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x77, 0x61,
	0x79, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x42, 0x79, 0x44, 0x61, 0x79, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x77, 0x61, 0x79, 0x2e, 0x50, 0x75,
	0x73, 0x68, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x42,
	0x79, 0x44, 0x61, 0x79, 0x54, 0x6f, 0x42, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_soloway_proto_rawDescOnce sync.Once
	file_api_grpc_soloway_proto_rawDescData = file_api_grpc_soloway_proto_rawDesc
)

func file_api_grpc_soloway_proto_rawDescGZIP() []byte {
	file_api_grpc_soloway_proto_rawDescOnce.Do(func() {
		file_api_grpc_soloway_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_soloway_proto_rawDescData)
	})
	return file_api_grpc_soloway_proto_rawDescData
}

var file_api_grpc_soloway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_grpc_soloway_proto_goTypes = []interface{}{
	(*BqConfig)(nil), // 0: soloway.BqConfig
	(*GsConfig)(nil), // 1: soloway.GsConfig
	(*Period)(nil),   // 2: soloway.Period
	(*PushPlacementStatByDayToBQRequest)(nil),  // 3: soloway.PushPlacementStatByDayToBQRequest
	(*PushPlacementStatByDayToBQResponse)(nil), // 4: soloway.PushPlacementStatByDayToBQResponse
}
var file_api_grpc_soloway_proto_depIdxs = []int32{
	0, // 0: soloway.PushPlacementStatByDayToBQRequest.bq_config:type_name -> soloway.BqConfig
	1, // 1: soloway.PushPlacementStatByDayToBQRequest.gs_config:type_name -> soloway.GsConfig
	2, // 2: soloway.PushPlacementStatByDayToBQRequest.period:type_name -> soloway.Period
	3, // 3: soloway.SolowayService.PushPlacementStatByDayToBQ:input_type -> soloway.PushPlacementStatByDayToBQRequest
	4, // 4: soloway.SolowayService.PushPlacementStatByDayToBQ:output_type -> soloway.PushPlacementStatByDayToBQResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_grpc_soloway_proto_init() }
func file_api_grpc_soloway_proto_init() {
	if File_api_grpc_soloway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_soloway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BqConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_soloway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GsConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_soloway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Period); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_soloway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushPlacementStatByDayToBQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_soloway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushPlacementStatByDayToBQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_soloway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_soloway_proto_goTypes,
		DependencyIndexes: file_api_grpc_soloway_proto_depIdxs,
		MessageInfos:      file_api_grpc_soloway_proto_msgTypes,
	}.Build()
	File_api_grpc_soloway_proto = out.File
	file_api_grpc_soloway_proto_rawDesc = nil
	file_api_grpc_soloway_proto_goTypes = nil
	file_api_grpc_soloway_proto_depIdxs = nil
}
