name: deploy-master

on: workflow_dispatch

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PHRASE }}
          script: |
            ${{ secrets.TO_DIR }}
            echo '${{ secrets.SERVER_PASS }}' | sudo -S docker-compose up -d --build ${{ secrets.DOCKERHUB_CONTAINER_ID }} --pull --no-cache