name: docker-push-yos

on: workflow_dispatch

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Git config
        run: git config --global url."https://${{ secrets.GH_PERSONAL_API_KEY }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Check dependencies
        run: |
          go mod tidy
          go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -vet=off ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_CONTAINER_ID }}:yos
          secrets: github_token=${{ secrets.GH_PERSONAL_API_KEY }}